"""Add enterprise settings to tenant

Revision ID: 18d9c8c96037
Revises: 9a9be2530014
Create Date: 2026-06-05 21:02:17.988457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d9c8c96037'
down_revision: Union[str, Sequence[str], None] = '9a9be2530014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('dlp_model', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('dlp_api_base', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('dlp_api_key', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('siem_webhook_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('hitl_webhook_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('monthly_budget', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('current_spend', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'current_spend')
    op.drop_column('tenants', 'monthly_budget')
    op.drop_column('tenants', 'hitl_webhook_url')
    op.drop_column('tenants', 'siem_webhook_url')
    op.drop_column('tenants', 'dlp_api_key')
    op.drop_column('tenants', 'dlp_api_base')
    op.drop_column('tenants', 'dlp_model')
    # ### end Alembic commands ###
