"""Add policy dsl rules

Revision ID: 4e5394ade12b
Revises: 18d9c8c96037
Create Date: 2026-06-05 21:12:28.094554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5394ade12b'
down_revision: Union[str, Sequence[str], None] = '18d9c8c96037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('dsl_rules', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'dsl_rules')
    # ### end Alembic commands ###
