"""add rbac models

Revision ID: 72f5a2ab6e18
Revises: 4e5394ade12b
Create Date: 2026-06-05 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f5a2ab6e18'
down_revision: Union[str, Sequence[str], None] = '4e5394ade12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    op.create_table('role_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_bindings_id'), 'role_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_role_bindings_tenant_id'), 'role_bindings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_user_id'), 'role_bindings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_bindings_user_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_tenant_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_id'), table_name='role_bindings')
    op.drop_table('role_bindings')
    
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
